# Generated by Django 4.2.7 on 2023-12-17 20:26

from django.db import migrations, models
import newsletter_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter_app', '0002_alter_newsletter_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='date_start',
            field=models.DateField(default=newsletter_app.models.get_date_now, verbose_name='Дата старта рассылки'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='period_send',
            field=models.CharField(choices=[('DAILY', 'Раз в день'), ('WEEKLY', 'Раз в неделю'), ('MONTHLY', 'Раз в месяц')], default='WEEKLY', max_length=20, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status_send',
            field=models.CharField(choices=[('CREATED', 'Создана'), ('STARTED', 'Запущена'), ('COMPLETED', 'Завершена')], default='CREATED', max_length=20, verbose_name='Статус рассылки'),
        ),
    ]
