# Generated by Django 4.2.7 on 2023-12-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter_app', '0005_remove_newsletter_user_alter_newsletter_status_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='client',
        ),
        migrations.AddField(
            model_name='message',
            name='client',
            field=models.ManyToManyField(to='newsletter_app.client', verbose_name='Клиент'),
        ),
    ]
