# Generated by Django 4.2.7 on 2023-12-05 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsletter_app', '0006_remove_newsletter_client_message_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_send', models.TimeField(verbose_name='Время рассылки')),
                ('date_send', models.DateField(blank=True, null=True, verbose_name='Дата рассылки')),
                ('period_send', models.CharField(choices=[('day', 'Раз в день'), ('week', 'Раз в неделю'), ('month', 'Раз в месяц')], default='week', max_length=20, verbose_name='Периодичность')),
                ('status_send', models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('completed', 'Завершена')], default='created', max_length=20, verbose_name='Статус рассылки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='date_send',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='message',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='period_send',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='status_send',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='time_send',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='client',
            field=models.ManyToManyField(to='newsletter_app.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='subject',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тема сообщения'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст сообщения'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер клиента'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AddField(
            model_name='options',
            name='message',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='newsletter_app.newsletter', verbose_name='Сообщение'),
        ),
    ]
