# Generated by Django 4.2.7 on 2023-12-05 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter_app', '0008_alter_newsletter_options_alter_options_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='user',
            new_name='owner',
        ),
    ]
