# Generated by Django 4.2.7 on 2023-12-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter_app', '0009_rename_user_client_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
    ]
