# Generated by Django 4.2.7 on 2023-12-06 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter_app', '0010_alter_client_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='owner',
        ),
    ]
