# Generated by Django 4.2.7 on 2023-12-08 23:48

from django.db import migrations, models
import newsletter_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter_app', '0011_remove_newsletter_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='date_send',
        ),
        migrations.RemoveField(
            model_name='options',
            name='time_send',
        ),
        migrations.AddField(
            model_name='options',
            name='date_start',
            field=models.DateField(default=newsletter_app.models.get_date_now, verbose_name='Время рассылки'),
        ),
    ]
